import { expect, test } from '@playwright/test'
import { demoOriginal, demoReplacement } from '../src/sample'
test('inline review rejects, accepts, and undoes as one editor action', async ({ page }) => {
  await page.goto('/')
  const editor = page.getByRole('textbox', { name: 'Markdown editor' })
  await page.getByRole('button', { name: 'Preview an inline edit' }).click()
  await expect(page.getByRole('region', { name: 'Suggested edit' })).toContainText(demoReplacement)
  await page.getByRole('button', { name: 'Reject', exact: true }).click()
  await expect(editor).toContainText(demoOriginal)
  await page.getByRole('button', { name: 'Preview an inline edit' }).click()
  await page.getByRole('button', { name: 'Accept edit' }).click()
  await expect(editor).not.toContainText(demoOriginal)
  await expect(editor).toContainText(demoReplacement)
  await page.getByRole('button', { name: 'Undo edit' }).click()
  await expect(editor).toContainText(demoOriginal)
})
test('typing invalidates an outstanding proposal', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Preview an inline edit' }).click()
  await page.getByRole('textbox', { name: 'Markdown editor' }).press('ArrowRight')
  await page.keyboard.type('Changed ')
  await expect(page.getByRole('button', { name: 'Accept edit' })).toHaveCount(0)
  await expect(page.getByRole('status')).toContainText('draft changed')
})
test('paired browser opens a file, reviews a fixture rewrite, saves and reopens exact text', async ({
  page,
}) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Connect local agent', exact: true }).click()
  await page.getByLabel('Companion address').fill('http://127.0.0.1:43124')
  await page.getByLabel('Pairing token').fill('automated-test-token-not-a-real-secret')
  await page.getByRole('button', { name: 'Connect companion', exact: true }).click()
  await page.getByRole('button', { name: 'Open local file' }).click()
  const editor = page.getByRole('textbox', { name: 'Markdown editor' })
  await expect(editor).toContainText('Browser proof')
  await editor.click()
  await editor.press('ControlOrMeta+End')
  await editor.press('ArrowLeft')
  await editor.press('Home')
  await editor.press('Shift+End')
  await page.getByRole('button', { name: 'Suggest an edit' }).click()
  await page.getByRole('button', { name: 'Accept edit' }).click()
  await page.getByRole('button', { name: 'Save file', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Saved to the file')
  await page.getByRole('button', { name: 'Open local file' }).click()
  await expect(editor).toContainText('This sentence is clearer.')
  await expect(editor).not.toContainText('could be more clear')
})
test('narrow layout keeps editor and controls inside viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('textbox', { name: 'Markdown editor' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(
    true,
  )
  await page.getByRole('button', { name: 'Preview an inline edit' }).click()
  await expect(page.getByRole('button', { name: 'Accept edit' })).toBeVisible()
})
